---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.cache # includes bowers cache
  yarn: true

env:
  global:
    - JOBS=1
  matrix:
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower phantomjs-prebuilt greenkeeper-lockfile@1
  - bower --version
  - phantomjs --version

install:
  - yarn install --no-lockfile --non-interactive
  - bower install

before_script: greenkeeper-lockfile-update

script:
  - yarn lint:js
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

after_script: greenkeeper-lockfile-upload
